### ISSUE TITLE
Exception when moving around vertex in proof mode

### ISSUE THREAD

**Issue by jvdwetering** [zxcalc/zxlive#310]
Start with following graph:
![image](https://github.com/zxcalc/zxlive/assets/15610543/950e4ddb-7993-4c7c-98dc-d5cf1b0f4d07)
Apply 'decompose hadamard' and then fuse the left Z-spider to get:
![image](https://github.com/zxcalc/zxlive/assets/15610543/95209f1c-2070-4c2f-81aa-71a245a49f32)
Now move one of the X-spiders. A disembodied pi/2 phase will appear and the following exception is thrown:
```Traceback (most recent call last):
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\mainwindow.py", line 273, in tab_changed
    self.active_panel.update_colors()
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\editor_base_panel.py", line 94, in update_colors
    super().update_colors()
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\base_panel.py", line 111, in update_colors
    self.graph_scene.update_colors()
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\graphscene.py", line 194, in update_colors
    v.refresh()
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\vitem.py", line 123, in refresh
    self.update_shape()
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\vitem.py", line 192, in update_shape
    if self.ty == VertexType.H_BOX or self.ty == VertexType.Z_BOX:
       ^^^^^^^
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\vitem.py", line 110, in ty
    _ty: VertexType = self.g.type(self.v)
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jweteri\Documents\Projects\zxlive\../pyzx\pyzx\graph\multigraph.py", line 359, in type
    return self.ty[vertex]
           ~~~~~~~^^^^^^^^
KeyError: 0
```

**Comment by RazinShaikh** [comment]
I have been able to reproduce the issue with the following simplest graph. Fusion does not seem necessary; first decompose hadamard and then move the rightmost x spider.

<img width = 350 src=https://github.com/zxcalc/zxlive/assets/28257517/429b6bc3-0c5a-4f01-a016-4440fdfda2e2>

**Comment by jvdwetering** [comment]
I can't reproduce this now. Has this gotten fixed in some of the cleanup over the last few months?

**Comment by RazinShaikh** [comment]
This was fixed at some point as far as I can tell and I am not able to reproduce, so closing it now.
