### ISSUE TITLE
`segfault` while making proofs

### ISSUE THREAD

**Issue by Aerylia** [zxcalc/zxlive#357]
I've not yet found a reliable way to reproduce, but since there is no issue on it and I've been getting the segfault quite frequently, I thought I'd make an issue so we can track this problem. Segfault crashes the editor and zxlive needs to be restarted, discarding any unsaved progress.

Partial trace, there were many more such errors thrown:
```
Error calling Python override of QVariantAnimation::updateCurrentValue(): Traceback (most recent call last):
  File "/Users/griendar/miniforge3/envs/zxlive/lib/python3.10/site-packages/zxlive/vitem.py", line 411, in updateCurrentValue
    self.it.refresh()
  File "/Users/griendar/miniforge3/envs/zxlive/lib/python3.10/site-packages/zxlive/vitem.py", line 123, in refresh
    self.update_shape()
  File "/Users/griendar/miniforge3/envs/zxlive/lib/python3.10/site-packages/zxlive/vitem.py", line 174, in update_shape
    if self.ty == VertexType.H_BOX or self.ty == VertexType.Z_BOX:
  File "/Users/griendar/miniforge3/envs/zxlive/lib/python3.10/site-packages/zxlive/vitem.py", line 110, in ty
    _ty: VertexType = self.g.type(self.v)
  File "/Users/griendar/miniforge3/envs/zxlive/lib/python3.10/site-packages/pyzx/graph/multigraph.py", line 363, in type
    return self.ty[vertex]
KeyError: 13
Segmentation fault: 11
```

Error seems to be related to selecting pieces of the graph (cursor mode) in the proof mode. It might have be caused by an interaction with the undo/redo button.

**Comment by RazinShaikh** [comment]
This should most likely be fixed by https://github.com/zxcalc/pyzx/pull/301 as that was causing all these key errors
